apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: main
          env:
            - name: SERVER_URL
              value: {{ .Values.teamcity.serverUrl }}
            - name: DOCKER_IN_DOCKER
              value: "start"
          securityContext:
            privileged: true
          volumeMounts:
            - name: certificate
              mountPath: /etc/ssl/certs/ca-certificate.pem
              subPath: {{ .Values.caRootCertificate.secret.path }}
      imagePullSecrets: {{ .Values.image.pullSecrets }}
      volumes:
        - name: certificate
          secret:
            secretName: {{ .Values.caRootCertificate.secret.name }}