apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  username: {{ .Values.octopus.admin.username }}
  password: {{ .Values.octopus.admin.password }}
  dbConnection: "Server={{ .Values.octopus.db.host }},{{ .Values.octopus.db.port }};Database={{ .Values.octopus.db.name }};User={{ .Values.octopus.dbUser.login }};Password={{ .Values.octopus.dbUser.password }}"
  masterKey: {{ .Values.octopus.db.masterKey }}