apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: web-panel
      port: {{ .Values.service.port }}
      targetPort: 8111
  selector:
    app: {{ .Release.Name }}